# Generated by Django 4.2.1 on 2023-06-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash_can_detector', '0008_remove_camcard_quantity_remove_camcard_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='quantity',
            new_name='capacity',
        ),
    ]
